### ISSUE TITLE
点击登录按钮出错，怎么解决？

### ISSUE THREAD

**Issue by xubuhang** [ninty90/react-native-redux-demo#3]
<img width="970" alt="default" src="https://cloud.githubusercontent.com/assets/4189632/23058330/70851858-f52f-11e6-8e8b-30992e72962b.png">

**Comment by deju** [comment]
@xubuhang  我已更新支持最新版本，请重新构建该项目并运行试试。

**Comment by xubuhang** [comment]
@deju 你好，请问你修改了哪些内容？

**Comment by deju** [comment]
@xubuhang  我把RN升级到0.41版本了。
