### ISSUE TITLE
关于运行android版

### ISSUE THREAD

**Issue by Gqq475** [ninty90/react-native-redux-demo#4]
您好，我下载了您的这个项目代码，我注意到您这个只有ios版才能有登录界面。android版只是写了一些文字描述。我想把这个能在android上面运行出结果，我的做法是把index-ios-js里面的文件copy到index-android-js文件里面 但是很不幸的报错了。我想寻求一下您的帮助，应该怎样才能把这些功能可以在android上面运行起来呢 。希望您能指点迷津。如果方便的话 可以回复到我的邮箱里面 542764124@qq.com 谢谢。

**Comment by Gqq475** [comment]
您好 现在不报错了 但是出现的页面中缺好多东西 只有中间的输入框 下面按钮和上面的文字都没有出现 这是什么原因呢

**Comment by deju** [comment]
@Gqq475 这个属于样式兼容性问题。你可以试着调整下修复，或者移除复杂的样式，只保留两个交互按钮。

**Comment by Gqq475** [comment]
好的。谢谢我试试
