### ISSUE TITLE
iOS crash

### ISSUE THREAD

**Issue by narakai** [ninty90/react-native-redux-demo#5]
点击应用icon报错： Error: ENOENT: no such file or directory, lstat '/Users/laileon/Documents/WebProject/react-native-redux-demo/ios/build/ModuleCache/8LLUQBGHBDG2/AVFoundation-2W8OQOO5E005V.pcm-f12df917'

**Comment by deju** [comment]
@narakai 
是无法点开吗？可以清理掉build缓存。把` /Users/laileon/Documents/WebProject/react-native-redux-demo/ios/build/`该目录删除，重新打包试一试

**Comment by narakai** [comment]
work like a charm! 感谢
